### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by Paul0o7** [bradley-Amuj/Lichess-InGame-OpeningName#1]
Im using edge wich is based on chromium i downloaded zip then used the folder to load unpacked but it didnt work i also disabled my prettier lichess extension any hints?

**Comment by bradley-Amuj** [comment]
Thank you for the feedback 
I will look into the issue and make the relevant changes to the project

**Comment by bradley-Amuj** [comment]
with the new update, this issue has been resolved. Hope you enjoy using the extension.
